# Generated by Django 5.2.12 on 2026-04-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='image_path',
            field=models.CharField(blank=True, help_text='Например: "img/communities/study_group.jpg"', max_length=255, verbose_name='Путь к картинке'),
        ),
        migrations.AddField(
            model_name='community',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичное'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
        migrations.AlterField(
            model_name='community',
            name='members_count',
            field=models.IntegerField(default=0, verbose_name='Участников'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
