# Generated by Django 5.2.12 on 2026-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes_images/', verbose_name='Изображение'),
        ),
    ]
